#pragma once

// Additional definitions in C++ land. The interrupts.hpp header must be compatible
// with C to be included in the autogenerated C code that calls ours C++ interrupts.

#include "type_definitions.hpp"


uint32_t get_adc_update_number();
uint32_t get_hall_unobserved_number();
uint32_t get_hall_observed_number();
Readout get_latest_readout();

uint16_t get_temperature();
uint16_t get_vcc_voltage();
int16_t get_cycle_start_tick();
int16_t get_cycle_end_tick();


// Data queue
// ----------

void readout_history_reset();
bool readout_history_full();
bool readout_history_available();
Readout readout_history_pop();
