#pragma once


#ifdef __cplusplus
extern "C" {
#endif

void adc_interrupt_handler();
void dma_interrupt_handler();
void tim1_update_interrupt_handler();
void tim1_trigger_and_commutation_interrupt_handler();
void tim2_global_handler();


#ifdef __cplusplus
}

// The autogenerated code defaults to C which calls our functions above; otherwise *we* prefer using C++.

#include "interface.hpp"
#include "constants.hpp"


#include "FreeRTOS.h"
#include "queue.h"


extern uint32_t adc_update_number;
extern uint32_t hall_unobserved_number;
extern uint32_t hall_observed_number;

extern StateReadout latest_readout;


// Data queue
// ----------

extern QueueHandle_t readouts_queue;
extern StaticQueue_t readouts_queue_storage;
extern uint8_t readouts_queue_buffer[HISTORY_SIZE * sizeof(StateReadout)];


// Initialize the queue for data passing from interrupt.
void data_init();

// Initialize the angle tracking system on startup to read the initial hall sensor state.
void initialize_position_tracking();

// Setup ADC for reading motor phase currents.
void adc_init();

// Select which interrupts to handle.
void interrupts_init();

// Enable the timers to start the ADC and motor control loops.
void enable_timers();

// End ifdef __cplusplus
#endif